### ISSUE TITLE
Please provide English description in Google Play

### ISSUE THREAD

**Issue by zub2** [covid19cz/erouska-android#123]
Please provide English description in Google Play. While I understand the primary language is Czech, when no English is provided, Google Play offers machine translation that produces pearls like: "You should also help to increase the number of infected coronaviruses." (for "Přispějte i vy k tomu, aby nakažených koronavirem přibývalo méně."). The text can be seen here: https://play.google.com/store/apps/details?id=cz.covid19cz.erouska&hl=en, after you press the "Translate" button.

Similarly, in the Google Play app, in the "About this app" section, there is: "Thanks to eRouche you will protect yourself and others in your area.". I don't know if this machine translation, but "rouche" - even if somewhat related (https://en.wiktionary.org/wiki/rouche) does not sound right. :)

The strings don't seem to be present in this repo - or at least I have not found them, so no pull request is possible.

**Comment by simekadam** [comment]
Good point. Cc @davidvavra. Is this something we have now access to?

**Comment by davidvavra** [comment]
Yes we can update Play Store, but we should do it together with app localization. It's planned for next week.

**Comment by davidvavra** [comment]
We started with the translation today: https://covid19cz.oneskyapp.com/

**Comment by davidvavra** [comment]
English description is in Google Play, the app is translated to English, being released gradually.
