### ISSUE TITLE
Podpora AOSP

### ISSUE THREAD

**Issue by regnarg** [covid19cz/erouska-android#141]
Spousta lidí má čistý AOSP bez Google Services (např. LineageOS). Bylo by celkem užitečné, kdyby aplikaci šlo na takovém systému spustit.

**Comment by panda7789** [comment]
Myslím, že podle tohoto vyjádření #136 není možné používat aplikaci bez Google Services.

**Comment by regnarg** [comment]
V aktuální podobě ne, pravděpodobně bude třeba spoustu věcí předělat (pravděpodobně kompletně reimplementovat Firebase klienta, protože standardní Firebase SDK závisí na GMS). Pokud se nenajde nikdo jiný, pustím se do toho časem sám. Ale na takovéto věci je třeba myslet hned na začátku.

**Comment by regnarg** [comment]
Mimochodem, je celkem pokrytecké tvrdit o aplikaci, že "respektuje soukromí", když závisí na knihovnách a službách, které jsou ukázkovým příkladem pohrdání soukromím uživatelů...

**Comment by Kobzol** [comment]
Veškeré analytics knihovny a jakýkoliv monitoring, které není vyloženě nutný pro fungování aplikace, byl z aplikace vyhozen. Backend byl vytvořen na Firebase hlavně z časových a finančních důvodů, berte prosím v potaz, že aplikace vzniká jako dobrovolnický projekt. Firebase by jistě šel odstranit, ale pak by se musel vytvořit jiný způsob autentizace uživatelů a taky přepsat kompletně celý backend. Možná k tomu časem dojde, ale v současné době řešení závisí na Firebase.

**Comment by jkufner** [comment]
Chápu-li to správně, tak spárování telefonních čísel s ID vysílanými po bluetooth jsou uloženy kdo ví kde na Googlích serverech, dost možná i v zemi, která nemusí respektovat GDPR?

**Comment by Kobzol** [comment]
Data o ID zařízení leží v Evropě, aplikace respektuje GDPR - https://erouska.cz/gdpr.

**Comment by jkufner** [comment]
O aplikaci samotné nepochybuji, ale o tom úlozišti, které používá, už přesvědčen až tak moc nejsem.

**Comment by regnarg** [comment]
No v zásadě jsou dvě možnosti:
1. Napsat komunikaci s Firebase from scratch, bez použití googlího SDK, případně přihnout nějakou desktopovou klientskou knihovnu pro Firebase. Chápu, že takovou změnu asi nebudete chtít mergenout, ale asi není problém udržovat fork.
2. Přejít na jiný backend. Pokud by to bylo v plánu v rozumném časovém horizontu, asi je zbytečné vynakládat zbytečné úsilí na hackování Firebase. Samozřejmě v případě potřeby rád pomůžu, ale působilo to na mě, že dobrovolníků je dost a bottlenecky jsou jinde.

**Comment by regnarg** [comment]
Já nemám problém se stamotným uložením dat ve Firebase, tolik citlivých informací neobsahují. Za výrazně větší narušení soukromí považuju mít nainstalované na telefonu Google services.

**Comment by Kobzol** [comment]
Samozřejmě by bylo ideální, kdybychom měli vlastní infrastrukturu někde ve sklepě poslanecké sněmovny a používali plně anonymní crypto-safe decentralizovaný protokol. To by ale ta aplikace vznikla tak možná někdy příští rok. Současné řešení se snaží co nejvíce dbát na soukromí uživatelů, nemáme téměř žádnou analytiku kromě Crashlytics, veškerá data jsou uložena lokálně na telefonu a i pokud se je uživatel rozhodně dobrovolně nahrát na server, tak se odtamaď po 6 hodinách smažou (bez zálohy). Reálně naprostá většina lidí má účty na Gmailu, používá Facebook atd. Ve srovnání s tím, co dělá tato aplikace, odevzdávají "tech giantům" stonásobně více dat.

**Comment by davidvavra** [comment]
Ano, bylo to vědomé rozhodnutí postavit celé řešení nad Google službami a distributovat jenom přes Play Store. V rámci omezeného času to jinak nešlo a na soukromí dbáme opravdu hodně. Měnit to neplánujeme, ale pokud někdo chce vytvořit fork s kompletně jiným backendem nezávislým na Googlu, go ahead.

**Comment by regnarg** [comment]
>  a na soukromí dbáme opravdu hodně

Starost o soukromí uživatelů: my vás šmírovat nebudeme, ale pokud to chcete nainstalovat, musíte ne nechat šmírovat od Googlu (a dát mu neomezenou vzálenou kontrolu nad svým zařízením a  další lahůdky spojené s Play Services). Vy jste vtipálkové.

> V rámci omezeného času to jinak nešlo 

To prostě a jednoduše není pravda. Na tom backendu se toho děje tak málo, že jsou stovky srovnatelně jednoduchých způsobů, jak by se to bývalo dalo řešit.

**Comment by Kobzol** [comment]
Na backendu se toho opravdu děje málo, ale potřebovali jsme velmi rychle nahodit technologii, která dokáže škálovat na stovky tisíc uživatelů, která umožňuje ověřovat telefonní čísla, kterou si můžeme dovolit a s pomocí které se ten backend dá vytvořit za pár dnů. Pokud znáte nějakou alternativu (sto jich zase si myslím úplně nebude :slightly_smiling_face: ), rád zvážím, jestli by šlo použít něco jiného. Původně jsme backend měli postavený trochu jinak, ale realita je dle mého stejně taková, že na ničem jiném než GCP/Amazon/Azure pro hostování se to za takový krátký čas postavit nedalo, takže i kdyby tam ten Firebase nebyl, tak by to stejně leželo na serverech firem, které nejspíše moc nemáte v oblibě. Firebase nám navíc poskytl možnost ověření tel. čísla a jednoduchý způsob tvorby API a práce s DB a díky tomu jsme si ho nakonec zvolili.

Pokud bychom brali Play Services jako nepřekonatelné zlo, tak v podstatě nemusíme ani dělat aplikaci pro iOS, protože tam se taky bez App Storu a Applu člověk neobejde. Mrzí mě, že jsme přišli o uživatele bez Play Services, ale reálně naprostá většina lidí s Androidem tuto službu má, používá a neřeší ji (nebo ani neví, že existuje), proto jsme si vybrali Firebase, vzhledem k výše zmíněným tradeoffům. Pokud později backend změníme, tak budu rád, když se počet kompatibilních zařízení zvýší.
