### ISSUE TITLE
Spamming notification when battery saver on

### ISSUE THREAD

**Issue by redhead** [covid19cz/erouska-android#145]
When my phone turns on the battery saver (battery going low), whenever I start interacting with phone (lock screen, unlock), it starts to spam the notification about the "erouska doesn't work with battery saver", and makes my phone vibrate way too often.

Phone: Moto G7 Plus

**Comment by simekadam** [comment]
Thanks for reporting. This is a known issue. It is related to the fact that location services turns off when the screen goes off while battery saver is on. And the other way round.

**Comment by simekadam** [comment]
Should be fixed with next update.
