### ISSUE TITLE
Switch tracing on/off via automation apps

### ISSUE THREAD

**Issue by liskin** [covid19cz/erouska-android#149]
To make the app more battery friendly (#148, …) it might be helpful to be able to declare [safe](https://twitter.com/PetrSimecek/status/1249581211183390721) [zones](https://twitter.com/simekadam/status/1249601953090473987) where tracing is off and the app consumes no extra power.

There may be several ways to detect what a safe zone is:

* location
* known WiFI
* known BT devices
* audio/notifications profile

Supporting all of these seems unnecessarily complicated so perhaps it's best to leave it to existing automation tools ([Tasker](https://tasker.joaoapps.com/), [Automate](https://llamalab.com/automate/), [Locale](https://www.twofortyfouram.com/), [Bixby Routines](https://www.androidcentral.com/bixby-routines-how-they-work-galaxy-s10), …). Integration with the first three is achieved via [plugins](https://www.twofortyfouram.com/developer/) ([more info](https://tasker.joaoapps.com/plugins-intro.html)). Bixby Routines doesn't seem to be as extensible, but it can invoke [App Shortcuts](https://developer.android.com/guide/topics/ui/shortcuts):

<img src="https://user-images.githubusercontent.com/300342/79122531-2bb4ed80-7d98-11ea-99a9-2aa53f271cfa.jpg" height="400" /> <img src="https://user-images.githubusercontent.com/300342/79122280-93b70400-7d97-11ea-8096-ccaba5fd30f5.jpg" height="400" />

I think it's quite likely that Tasker/Automate/Locale can also invoke App Shortcuts so I'd start by adding these: one to disable tracking and another to enable it. Then we can test this in the wild and see if it does the job and see what interesting use cases the users come up with.

Oh and we'll get this for free: the possibility of putting on/off buttons on home screen. :-)

**Comment by davidvavra** [comment]
We are considering the simplest way which we could implement this. We would be happy to accept PR for App Shortcuts.

**Comment by simekadam** [comment]
This looks great. +1 for app shortcuts, that could be fairly simple.

**Comment by jendakol** [comment]
I did some research and unfortunately, app shortcuts are designed for slightly different use-case - to **open the app** in some state. In other words, I'm able to pause/resume the tracking but the app would be open in the same moment which is kind of unwanted. I'm now working on receiving broadcaster URL to pause/resume from other apps, I have to check compatibility with Tasker, Automate etc.

**Comment by davidvavra** [comment]
@jendakol I guess you can open the app and call finish() when it's done :)

**Comment by jendakol** [comment]
@davidvavra You are theoretically right, but I've faced a weird issue:
1) When I used intent opening main Activity, the intent in `onStart` was different than was the real one opening the app (so I couldn't recognize what's going on).
2) When I used new Activity (created just for this purpose), it worked nicely but the main activity was still open after that, like if it was added to the stack.

If you have an idea how to hack this... :smile:

**Comment by davidvavra** [comment]
@jendakol Pass some intent extras or intent action to the activity. Detect if you are launching from the shortcut based on it.

**Comment by jendakol** [comment]
@davidvavra I've tried to pass both custom action as well as `ACTION_VIEW`, both with extras - IIRC custom action didn't work at all, `ACTION_VIEW` cause opening the app with `ACTION_MAIN` like if the app was opened normally, no extras included - just completely different Intent than was started. I'll probably  try once again and write down all possibilities I'm trying :-(

**Comment by davidvavra** [comment]
@jendakol Let me copy code from Settle Up :)

```
    <shortcut
        android:shortcutId="add_transfer"
        android:icon="@drawable/ic_shortcut_add_transfer"
        android:shortcutShortLabel="@string/add_transfer">
        <intent
            android:action="SHORTCUT_ADD_TRANSFER"
            android:targetPackage="cz.destil.settleup"
            android:targetClass="cz.destil.settleup.gui.MainActivity" />
    </shortcut>
```

```
override fun onCreate(savedInstanceState: Bundle?) {
  if (isLaunchedFromShortcut() && isAddTransferShortcut()) {
   // navigate to add transfer screen
  }
}
```

```
private fun isLaunchedFromShortcut(): Boolean = intent.action?.startsWith("SHORTCUT")
            ?: false // if there is no action, it is started from widget
```

`private fun isAddTransferShortcut(): Boolean = intent.action == "SHORTCUT_ADD_TRANSFER"`

**Comment by jendakol** [comment]
@davidvavra Yeah, but these are _static_ shortcuts - I think they doesn't make sense in eRouška, we need to have _dynamic_ shortcuts to be able to reflect current state (scanning/paused).

**Comment by davidvavra** [comment]
@jendakol I would add two static shortcuts - for enabling and disabling. People who automate this will call the one they want.

**Comment by jendakol** [comment]
@davidvavra 

`onNewIntent` FTW :tada: 
Shortcuts will work :wink:

**Comment by davidvavra** [comment]
Backend guy discovering Android lifecycle 😱

**Comment by jendakol** [comment]
Solved in #175 .

**Comment by ceresek** [comment]
This is no longer available with current version (from play store), is it possible to get the automation back ?

**Comment by davidvavra** [comment]
Yes, we removed it due to time constraints and because the new version consumes much less battery, so the need of turning it off is minimal. Feel free to send us a pull request with the automation.

**Comment by jendakol** [comment]
Hi @ceresek,
from our findings, this function was almost not used at all and now the need for it is even smaller. If you insist on having it, either implement it by yourself or convince enough people to request such function here or through the support :smile:

**Comment by liskin** [comment]
As the original poster of this idea, I must say that since the wakelock issue was fixed (which was, iirc, fairly shortly after this workaround was implemented), battery usage has not been as issue **at all**, thus rendering this workaround unnecessary.

**Comment by ceresek** [comment]
The bad news is, the exposure notification API will display a user prompt every time it is `start()`ed, which means bye bye automation unless Google changes this behavior. So no PR.

As a small consolation, the service does pause gracefully when bluetooth is turned off, so if the user does not need bluetooth except for exposure broadcasts and scanning, the automation can simply manipulate bluetooth settings directly.
