### ISSUE TITLE
Battery drain!

### ISSUE THREAD

**Issue by Vict0rC** [covid19cz/erouska-android#162]
BetterBatteryStats version: 2.5-341
Creation Date: 2020-04-14 13:29:06
Statistic Type: **Unplugged to Current**
**Since 19 h 22 m 17 s** 
MODEL: MI 9
OS.VERSION: 4.14.117-perf-gbf4e3c0
Level lost [%]: Bat.: -72%(100% to 28%) [3,7%/h]
Voltage lost [mV]: (4344-3682) [34,2%/h]
Deep Sleep (): 2 s  0,0%
**Awake (Screen Off) (): 17 h 34 m 48 s  90,8%**
Screen On (): 1 h 47 m 27 s  9,2%

Wakelocks
**cz.covid19cz.erouska:LOCK (cz.covid19cz.erouska.eRouška): 15 h 37 m 25 s**  Count:5 80,7%

Processes
cz.covid19cz.erouska (cz.covid19cz.erouska.eRouška): Uid: 10454 Sys: 10 m 29 s  Us: 33 m 43 s  Starts: 6
*wakelock* (cz.covid19cz.erouska.eRouška): Uid: 10454 Sys: 27 s  Us: 33 s  Starts: 0

Network
10454 (Wifi) (cz.covid19cz.erouska.eRouška): 26.0 KBytes 0,0%

**Comment by simekadam** [comment]
We are working on making this better, but unfortunately holding a partial WAKE_LOCK is necessary to allow continuous scanning at the moment. Other variants yield unstable results.

**Comment by petacz** [comment]
Hi,
What if you would pause or decrease the scanning interval while in doze mode?
When the phone is stationary especially over night, it makes no sense to scan.

**Comment by simekadam** [comment]
There is no such thing as doze with eRouska on 😃
We thought about adding some smart autopause, but it gets tricky.
We are considering various approaches. And already testing some improvements to the scanner setup.

**Comment by petacz** [comment]
I meant Android Doze https://developer.android.com/training/monitoring-device-state/doze-standby

**Comment by simekadam** [comment]
I know. But because the app holds a partial wakelock it blocks the phone from dozing.

**Comment by davidvavra** [comment]
Last update brings removal of wakelock. That should improve battery significantly. Closing this issue, open new one if you still experience it.
