### ISSUE TITLE
Doesn't send international SMS

### ISSUE THREAD

**Issue by pkubanek** [covid19cz/erouska-android#165]
Probably doesn't send veryfications to internatiol numbers. I tried with my Chilean (+56), never received verification SMS. Probably should at least notify it's not sending to international numbers. Might try to debug that further..

**Comment by rejdi** [comment]
Works for me (+421, Slovakia)

**Comment by davidvavra** [comment]
Our SMS gateway should support all countries. @pkubanek What exact number you are trying? Send me PM to david.vavra@erouska.cz

**Comment by pkubanek** [comment]
Works now (after app update, which I am not sure was relevant).
