### ISSUE TITLE
No APK, f-droid, Google Prey Services dependent.

### ISSUE THREAD

**Issue by v60coffee** [covid19cz/erouska-android#178]
If one wants the app to be available to the widest circle of users, one should not restrict it to big brother's services. Lots of users have degoogled phones and you loose the good will of those. On top of that, collect PII and use privacy invading corporation's services?

Please try better next time, without proprietary nonsense that is GCM/Firebase.

I do not buy your explanations in other threads. You just went with a path of least resistance, to hell with privacy and users outside of reach of data miner corp. You are thus complacent in privacy shrinkage and are empowering evil corporation, enabling it.

**Comment by davidvavra** [comment]
This is not a place for discussion, only for actual bugs in the app. Please contact our support at info@erouska.cz

**Comment by jnpkrn** [comment]
@v60coffee Is my understanding that self-compiled app will remain
unusable?  That'd be dissapointing.

In fact I went that route and cannot register a phone number for
some reason, which could be explained like with Firebase - "approved"
app pairing.

**Comment by jnpkrn** [comment]
Got it, missed (along with OP) this was discussed already: #128, #141
