### ISSUE TITLE
eRouska messes bluetooth config and prevents from working Mi Band 2

### ISSUE THREAD

**Issue by Yanisin** [covid19cz/erouska-android#184]
Hi,
I use a Xiaomi Mi Band 2 with  Mi Fit and Mi Band Tools on my Samsung Galaxy A70. Once I installed erouska the Mi Fit can't attach to the Mi Band. If I clear all data of the bluetooth application the band starts working again (I can't tell if at this moment erouska is working I was not in vicinity of any other phone with erouska app), but after some while it gets broken again.

I didn't inspect the code handling the BLE, but are you sure you don't mess any other config you don't need?

**Comment by simekadam** [comment]
What is the Bluetooth app that you clear data of? eRouška?

**Comment by Yanisin** [comment]
> What is the Bluetooth app that you clear data of? eRouška?

Of the system application that handles the bluetooth. Sorry I'm not really an expert. I just tried to clean whatever whereever I found. But.. if you instruct me, what exactly do I can try to repeat step by step maybe including some debug via ADB and tell the results.

**Comment by davidvavra** [comment]
This issue is not happening in v2 version of the app, closing.
