### ISSUE TITLE
Location service condition

### ISSUE THREAD

**Issue by cima** [covid19cz/erouska-android#190]
Why is the location service of system used as a condition for entire service to run?

* Condition [CovidService.kt](https://github.com/covid19cz/erouska-android/blob/master/app/src/main/kotlin/cz/covid19cz/erouska/service/CovidService.kt#L149)
* Change listener [LocationStateReceiver.kt](https://github.com/covid19cz/erouska-android/blob/master/app/src/main/kotlin/cz/covid19cz/erouska/receiver/LocationStateReceiver.kt#L23)

If the service is suppose to be privacy focused GPS shoudn't be a condition to have the application operational. Beside privacy the GPS radio is generally a battery killer.

It has been pointed out in [google play review by Igor Khavkine](https://play.google.com/store/apps/details?id=cz.covid19cz.erouska&reviewId=gp%3AAOqpTOEbjE4A92uf-zwuquErlbW1XZvjeZQYzwVASAA5v6RUIPQirc8Ij0hCZHqAjCcjRzA0DWabq2x76nYC)

**Comment by Kobzol** [comment]
This is (sadly) required by Android, otherwise BLE scanning will not work. https://stackoverflow.com/questions/33045581/location-needs-to-be-enabled-for-bluetooth-low-energy-scanning-on-android-6-0

There is nothing that we can do about it, so I'm going to close this issue.

**Comment by jendakol** [comment]
> Beside privacy the GPS radio is generally a battery killer.

I'd like to add that as you're able to find this in the source code, you're surely able to also find that we DON'T use the GPS (and the listener you've pointed to reacts to change of the permission, not the location itself).

**Comment by cima** [comment]
I am aware of your application doesn't use GPS data, but google's application does everytime GPS radio is on. So necessity to have GPS on allows other evil applications to use it and one has difficulty to master when these are allowd to spy on you and when not.

Anyway if **google is so arogant** that doesn't let android to use BLE without enabled GPS there is nothing you can do about it.

**Comment by jendakol** [comment]
@cima Actually, I don't want to be a devil's advocate but there _is_ a reason why Google did this - BLE advertising can be (in very limited scope) used to localization - read more [at developers.google.com](https://developer.android.com/guide/topics/connectivity/bluetooth#Permissions).
