### ISSUE TITLE
Cannot activate phone number

### ISSUE THREAD

**Issue by erikstoklasa** [covid19cz/erouska-android#192]
If you activate your phone number on your phone, then uninstall the app and afterwards install it and try to use it again, it will not allow you to activate your phone number and you can not use the app.
![Screenshot_20200420-155059~2](https://user-images.githubusercontent.com/45731908/79759329-d55b2800-831e-11ea-90d9-1810c38b4175.png)

**Comment by Kobzol** [comment]
Hi, just to clarify:
1) Did you register your phone number immediately or "later" during the first installation?
2) After the reinstallation, did you try to register your phone immediately or "later"?

**Comment by erikstoklasa** [comment]
Hi,
1) First I activated my phone number immedeiately
2) Then I tried to activate it immediately and later but both did not work

**Comment by Kobzol** [comment]
And after the reinstallation, when you tried to activate the phone number *immediately*, did you receive this specific error ("Phone number XXX cannot be activated because you have used it...") or a different error?

**Comment by erikstoklasa** [comment]
After the reinstall when activating it immediately, it did not show any error, it did not even send me the SMS with the code

**Comment by Kobzol** [comment]
I see. You can only "attach" your phone number to an anonymous account (= account created by clicking on "I'll finish the verification later") if there is no existing account with the same phone number.
It should however be still possible to register when you open the app for the first time. If you are not receiving the SMS, it might be a carrier issue, which we sadly cannot resolve.
As a last resort, try to remove the data of the application in Android settings, then do the same for Google Play Services, then uninstall the app and install it again. If that still does not help and the SMS does not arrive, I'm afraid that we cannot help any further.

**Comment by erikstoklasa** [comment]
You're right it works, but honestly, it's not convinient maybe try to make it so you can attach your phone number even when you're clicking the I'll activate later

**Comment by Kobzol** [comment]
I'm glad that it helped. What you mention is not possible for technical reasons, because then you could have two (different) accounts with the same phone number. When you log in for the first time, you can log into an existing account, but when you are already logged in with an anonymous account in the app, switching an account would mean that all of your data would be wiped away, which would defeat the purpose of registrating anonymously in the first place.
