### ISSUE TITLE
Too much notitifications on low battery

### ISSUE THREAD

**Issue by literakl** [covid19cz/erouska-android#195]
It happened on sunday when my battery dropped under 15% and system activated a battery saver. When the screen was locked I was receiving new notification to stop the battery saver every few minutes.

Android 9, Nokia 8

**Comment by Dazix** [comment]
Same for me. (same mobile, same OS version). And one more thing I can't remove notification with warning that app is inactive, even when I charged battery, activate / deactivate app. The notification is still here and can't be removed.

**Comment by davidvavra** [comment]
This issue is not happening in v2 version of the app, closing.
