### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by orangesunny** [covid19cz/erouska-android#204]
Thanks for the app!

As there are people living in (and visiting) the Czech Republic who feel more comfortable while using different languages, it would be nice to have the app and store description multilingual to grow the userbase.

We would be happy to host the translations on https://weblate.org for free as we do for all libre projects. The community on https://hosted.weblate.org/ is open and very friendly, and the translations would be ready very soon. 

Also, checks and other features will ensure quality. Strings propagation with the iOS version is for sure to reduce the needed amount of translators’ work. Tight integration saves the time of the developers.

**Comment by davidvavra** [comment]
We are using OneSky for localization. Feel free to contribute there: https://covid19cz.oneskyapp.com/

**Comment by orangesunny** [comment]
I see. Good luck!
Is there any ETA for the multilingual version? 

I started this issue as I met tumbleweed and dust settled in that OneSky project. 😞  Nearly nothing changed in last week there. It’s more about getting the translations done on 100% than about my contribution. OneSky doesn’t offer many features, so far I saw only 0 next to "Translation memory". Keeping things libre would be a nice bonus.

**Comment by davidvavra** [comment]
Well the current app has English and Czech, so it's multilingual.

Next update should bring also Vietnamese, Russian, Ukrainian and Romanian.

OneSky UX is not great, but it was the only free tool we could find. Now it's tied to our build using API integration, so it's probably too expensive for us to migrate to another tool.

**Comment by orangesunny** [comment]
> Well the current app has English and Czech, so it's multilingual.

I see, so just settings in the app are missing. 

> Next update should bring also Vietnamese, Russian, Ukrainian, and Romanian.

Great to hear that. But seems really unfinished in OneSky.

> OneSky UX is not great, but it was the only free tool we could find. Now it's tied to our build using API integration, so it's probably too expensive for us to migrate to another tool.

I understand. Weblate is free for libre projects and the integration is: just tell me. So free :) It pulls the translation files from here. Then, PRs will be created here by [Weblate](https://github.com/weblate) user, automatically or by click in Weblate. Or by using [wlc](https://docs.weblate.org/en/latest/wlc.html#wlc). PRs include all the credits to translators etc.
