### ISSUE TITLE
Only activate when home wifi out of range

### ISSUE THREAD

**Issue by andree182** [covid19cz/erouska-android#205]
The battery drain is relatively severe and 99% of the time it doesn't make sense to have the app running while home (where most of the people are most of the time, these days).

Would it be possible to check e.g. every 5 minutes if mobile is connected to "home wifi" and only activate if not? I realize it may be niche use, so maybe this could get hidden in the advanced settings somewhere...

**Comment by felagund** [comment]
On the other hand, in case you entertain visitors at home (whether you should do that or not is a different matter, but it certainly happens), you would still need the app activated.

**Comment by andree182** [comment]
In this particular case, you'll likely get the bad news from those friends/family, that they are in fact sick (contrary to random person from restaurant/shop/street). But yeah, for sure there will be counterarguments for anything....

**Comment by felagund** [comment]
Well, it could also be a plumber and his aide that you don't really know that came to fix your sink. But I agree that such an option might make sense for some people.

**Comment by simekadam** [comment]
Sorry for the later reply. We are indeed looking into the possibility to set a safe zone based on your home/work wifi.
Also even better, we are about to release an update that significantly cuts down the battery consumption.

**Comment by davidvavra** [comment]
@jendakol is preparing guides how to enable this with Tasker or Automate apps. Do you have some updates Jenda?

**Comment by davidvavra** [comment]
Battery consumption should be minimal in v2 version of the app. It should not be needed to turn off the app on home wifi.
