### ISSUE TITLE
Forced portrait mode

### ISSUE THREAD

**Issue by felagund** [covid19cz/erouska-android#206]
I use my phone in landscape by default. When first run the app is in portrait. It would be nice if it could work in landscape too stright away. After setting the app and restarting, it goes to landscape.

**Comment by simekadam** [comment]
Would you please elaborate on this? 

> After setting the app and restarting, it goes to landscape.

**Comment by felagund** [comment]
No prostě když jsme si to nainstaloval, tak to trvalo na tom mi to ukazovat jako portrét, i když mi telefon ležel v landscapu. Mám telefon s klávesnicí, takže je vždy v landscape, ledažeho explicitně přepnu do portrétu. Došlo k tomu, že ta úvodní obrazovka byla o devadesát stupňů otočená k mé klávesnici a k tomu, jak jsem se na ní díval.

**Comment by simekadam** [comment]
Muzu se zeptat co to je za device? 
Appka je lockla do portrait modu, takze jestli to pak zacne fungovat, tak to musi byt nejaky override na strane toho telefonu.

**Comment by felagund** [comment]
Tenhle https://www.indiegogo.com/projects/cosmo-communicator#/. V ČR jich je tak do sta kusů a podobně starší verze jménem "Gemini". Jako já to přežiju a nerozumím technickým důvodům, proč by to vždycky mělo být v portét módu, ale čistě z uživatelského hlediska nevidím důvod, proč by to nerespektovalo úhel, v kterém uživatel telefon drží.

**Comment by davidvavra** [comment]
Portrait jsme locknuli na začátku, protože není jiný design na landscape a nebyl v hackathon módu čas testovat rotace. Teď bych to klidně zapnul, imho nevadí že to nebude vypadat kdovíjak na landscape, lepší než blokovat rozhodnutí uživatele.

**Comment by simekadam** [comment]
Asi bysme museli hromadu layoutu wrapnout do scrollview. Ale proč ne.

**Comment by davidvavra** [comment]
Nechceš na tohle @felagund poslat pull request?

**Comment by felagund** [comment]
Já vůbec androidí aplikace dělat neumím, takže ne, sorry.
