### ISSUE TITLE
When setting up, I need to enter my number. The phone knows my number, it could get it automatically

### ISSUE THREAD

**Issue by felagund** [covid19cz/erouska-android#207]
After the confirmation sms is sent, it gets copy pasted to the app automatically. But I had to enter my phone number manually. I would expect the app to get it on its own. My phone is a dual-SIM with one physical SIM and one eSIM - not sure if that is realted. I would expect the app to let me choose which nubmer to use or to enter a different number in case I use two phones or something.

**Comment by davidvavra** [comment]
We decided not to prefill phone number, because it would require scary permission for the users. And even with the permission, it's not guaranteed on all devices.
