### ISSUE TITLE
Untranslated (czech) static text

### ISSUE THREAD

**Issue by radeksimko** [covid19cz/erouska-android#216]
There is text inside the app which still appears to be only in Czech language and probably should be translated to english (and any other language the app supports), relatedly some links link to Czech version of relevant websites when they have English versions and users should probably be directed there instead when the app in English.

### My data screen

<img src="https://user-images.githubusercontent.com/287584/87254126-34d95780-c478-11ea-9c37-8b2e44924e16.png" width="150px">

### Many sections of the Help screen

<img src="https://user-images.githubusercontent.com/287584/87254128-373bb180-c478-11ea-8694-f550d96cee58.png" width="150px">

### Links from the Contacts screen

<img src="https://user-images.githubusercontent.com/287584/87254129-386cde80-c478-11ea-99fc-3312651ec311.png" width="150px">

**Comment by davidvavra** [comment]
Hi Radek! English translation is not complete. Can you help here? https://covid19cz.oneskyapp.com/collaboration/translate/project/project/359388 When everything is translated, I can update it in the app remotely (via Firebase Remote Config)

**Comment by radeksimko** [comment]
I would be more than happy to help, but it seems that some phrases shown on the screenshots above are not available for translation there - or the search doesn't seem to be finding these:

![Screenshot 2020-07-21 at 09 18 24](https://user-images.githubusercontent.com/287584/88030454-28699480-cb33-11ea-8afe-450b07add387.png)

How often is the data synced with the codebase? Is it possible that it's just out of date? Relatedly - should I install any latest beta version which has the most up-to-date translations?

**Comment by davidvavra** [comment]
You can filter out not translated phrases here: https://covid19cz.oneskyapp.com/collaboration/translate/project/project/359388/language/45#/filter/not-yet-translated/

Most of the phrases are synced with app update, which is not a priority now, because we are focusing on app rewrite based on Apple/Google protocol.

**Comment by radeksimko** [comment]
I think I finally figured out where my confusion comes from - there are some phrases which are not available for translation via OneSky, specifically those in this file:
https://github.com/covid19cz/erouska-android/blob/7e064a1b481441815688e07d12ec9fd1fa8e0821/app/src/main/res/xml/remote_config_defaults.xml

Is it best to just PR a change into `remote_config_defaults.xml` adding entries such as `dataCollectionMarkdown_en`, or is there any reason why these phrases are in that file, instead of `/app/src/main/res/values-<LANG-CODE>`?

**Comment by davidvavra** [comment]
Those phrases are configurable though service Firebase Remote Config, they are not hardcoded like those in `values-<LANG>` folder. We can update them without updating the app. So the best way is probably sending a PR to `remote_config_default.xml`, I can update them in Remote Config and it will be immediately visible to the users. We don't plan any app update until the big rewrite with A/G protocol.

**Comment by radeksimko** [comment]
Gotcha, thanks - will send a PR 🔜  which I think could then close this issue.

**Comment by davidvavra** [comment]
Thanks a lot! I also updated the phrases in the Remote Config, you can test it in the current app.
