### ISSUE TITLE
On Slovak Android app fallbacks to English language, should fallback to Czech language instead

### ISSUE THREAD

**Issue by brozkeff** [covid19cz/erouska-android#344]
On Slovak Android the fallback language seems to be English, however for Slovaks living in Czechia it would be more meaningful to have the app in Czech.

So if the app is Czech and English language only, the logic should be:

1. Czech Android -> Czech eRouška2
2. Slovak Android -> fallback to Czech eRouška2
3. English Android -> English eRouška2
4. any other language version of Android -> fallback to English eRouška2

+ Option to manually force another language would be useful.

**Comment by davidvavra** [comment]
@brozkeff Can you help translating the app to Slovak? We welcome contributions here: https://covid19cz.oneskyapp.com/

**Comment by davidvavra** [comment]
Btw there is a feature of Android for this: order of languages. In Android settings, you can set order of languages you understand. If you are Slovak and understand Czech, you can set up order as:

1. Slovak
2. Czech

Apps which are in Slovak will be in Slovak, apps which are not in Slovak but in Czech will be in Czech and apps which are not in Slovak or Czech will be in default language (usually English).

**Comment by vandus** [comment]
I have spent some time translating to Slovak. Could you please add it to the app so others can benefit? :)

**Comment by davidvavra** [comment]
Thanks for the contribution! We will add Slovak once Remote Config strings are translated too.
