### ISSUE TITLE
Negotiate bilateral exchange of backend DB data of infected IDs between CZ, DE and other countries

### ISSUE THREAD

**Issue by brozkeff** [covid19cz/erouska-android#349]
Until a pan-European deal exists to share DBs of lists of infected ppl among countries so that eRouška2 can trigger an alert if it finds captured beacons of German Corona-Warn users etc. is there a possibility to make bilateral agreements on daily exchange of this data between e.g. Czech backend db and German backend db? Would it be GDPR and privacy-wise compliant without further explicit acceptance by all users?
Could Czech app accept another type of COVID-positive test code e.g. from Germany?

**Comment by stepansonsky** [comment]
Yes, It's our top priority for us now. We're in touch with Google, Apple and other national Covid apps teams to bring this feature in near future.

**Comment by liskin** [comment]
What is the recommended approach for users before this deal is done? If I move to another country, should I uninstall eRouška a install their app? Or should I wait for a few days so that I'm still notified about risky contacts in the past? Will this impact my ability to inform risky contact in the new country?

**Comment by davidvavra** [comment]
You can have multiple apps installed in the same time. eRouška will notify you about infected Czechs, Corona-Warn-App (for example) will notify you about infected Germans.

**Comment by liskin** [comment]
Installed, yes, but not active. :-(

![Screenshot_20201007-163313_Google Play services](https://user-images.githubusercontent.com/300342/95345406-fa3a5c00-08ba-11eb-9040-2ab5caf1f8fb.png)

**Comment by liskin** [comment]
So, um, is there any progress in this issue? I just got a positive test result from the NHS UK so it would be lovely if eRouška could notify the people who were near me on the way to the airport and inside the airport...

**Comment by davidvavra** [comment]
Yes, we are working on the interoperability in branch `feature/efgs`

**Comment by davidvavra** [comment]
We are still working on this. It's currently held up by lawyers due to GDPR issues.

**Comment by davidvavra** [comment]
We are still working on this. It's no longer held up by GDPR lawyers and now it's up to us.
