### ISSUE TITLE
Support for Android 5

### ISSUE THREAD

**Issue by ondracek-lukas** [covid19cz/erouska-android#352]
Hello.

Would it be possible to lower minSdkVersion back to 21?

According to Google [1], Exposure Notifications API may work on some phones with Android 5:
> For your app to work on all devices, set your minSdkVersion to version 6.0 (API level 23) or higher. The framework works on some devices as low as version 5.0 (API level 21), so using this version is an option to increase the number of devices eligible. If you decide to set the minSdkVersion to API level 21, you should test your app on the most popular Android 5.0 devices in your country to ensure that your app works as intended.

[1] https://developers.google.com/android/exposure-notifications/exposure-notifications-api

Unless there are other technical reasons,
I would prefer some disclaimer for phones with this version instead of forbidding them.

I've tried to modify the app myself for my Sony Xperia Z1 Compact with Android 5.1.1;
I was able to spawn it, but the API rejected my signature of the app:

```code
I/ExposureNotification( 2439): Utils#isSupported enabled=true [CONTEXT service_id=236 ]
I/ExposureNotification( 2439): Utils#isBluetoothSupported requireMultiAdvertisement=false [CONTEXT service_id=236 ]
I/ExposureNotification( 2439): isDeviceSupported=true, isBluetoothSupported=true, BluetoothAdapter.isMultipleAdvertisementSupported=false [CONTEXT service_id=236 ]
I/ExposureNotification( 2439): Denied cz.covid19cz.erouska.dev:9E0D7AF6DC00CD39E92394DD154BC2644D17B82AC216C529ABC22EFC56437050: not on whitelist [CONTEXT service_id=236 ]
W/ExposureNotification( 2439): Reject the api access due to the caller is not whitelisted [CONTEXT service_id=236 ]
```

Thanks for your work.

**Comment by davidvavra** [comment]
Yes, theoretically it might work on some Android 5 devices. But we decided to keep minSdk to version 23. The reasons are:
- we will need more testing capacity, both in people and phones
- we will need more support capacity for these users
- this extra effort is not worth for few percent of extra users
- we looked at code of similar apps (like Germany's Corona-Warn-App) and they also have 23

**Comment by ondracek-lukas** [comment]
Thanks for explanation.
You're right that there are only few such applications supporting Android 5 (such as that of [South Africa](https://play.google.com/store/apps/details?id=za.gov.health.covidconnect)),
but I still think that even untested and supportless app may be useful for some people (minimizing that extra effort).
Please, reconsider the following options:

#### 1) One-character change + disclaimer:
* change just the minSdk in source;
* write to the description that
	* it's guaranteed to work only on Android 6 and higher and
	* that no support will be provided for Android 5.

I suppose that the worst-case scenario is the crash of the application
leading user to uninstall it and so recovering the previous state of his phone,
isn't it?

Even without any testing, this may only extend number of supported devices.

The downside of this solution is that people may not know their OS version
and the disclaimer might discourage them from installing the app.


#### 2) In-app disclaimer:
* modify the app to first check the OS version and inform user that
	* either it is fully functional (6+),
	* or the device may be unsupported and he should uninstall it in case of issues (5);
* write to description that the app will inform user in a very rare case of unsupported device.

I suppose that the application will not crash before trying to contact the API.
This is also supported by [the COVID app of Uruguay](https://play.google.com/store/apps/details?id=uy.gub.salud.plancovid19uy),
which provides some limited functionality for Android 5 and uses Exposure Notification API for higher versions.

This requires a little more effort in changing the app,
but the in-app disclaimer may inform concrete people not to contact you for further support.


I can test it on two phones:
* Sony Xperia Z1 Compact (D5503) with Android 5.1.1, and
* Samsung Galaxy Xcover 3 (SM-G388F) with Android 5.1.1.


#### 3) Publishing modified APK only on github:
* probably possible automatically through artifacts.

This has no influence on vast majority of people,
but helps only few individuals
so it's not worth it for you to do it.

In this case, I can try to prepare a pull request.
It will took me some time to learn how your project works,
but still not as much as unlocking and manually reinstalling the two affected devices.

**Comment by davidvavra** [comment]
Hi, thanks for a detailed answer. Options 1) and 2) are out of the question now, because no matter what disclaimers we put out there, users will still write to our support which is currently overloaded. We don't have a full capacity to help all Android 6+ users.

But we don't have a problem with publishing signed APK with Android 5.0 here in this repo. It might help a few technical users like yourself. I can do that one time and I will accept a pull request for some automation. What do you think?

**Comment by ondracek-lukas** [comment]
Hi,
great, thank you.

So I'll try to modify .github/workflows to build also production 5+ version beside the two (prod and dev) and include it in generated github artifact, which seems to be downloadable by all registered users of github.

**Comment by davidvavra** [comment]
I built current develop with minSdk 21 manually and signed it with prod certificate, can you test it on your devices? https://drive.google.com/file/d/1zm71VADGQmO5LFo72xN5E1wcstXBWSX6/view?usp=sharing

**Comment by ondracek-lukas** [comment]
I'll test in a few hours, thanks.

**Comment by ondracek-lukas** [comment]
Unfortunately, it crashed on both devices...

I compared the logs of the two v5 devices with working v6 device
and it worked up to starting scanning.

Then advertising failed on Xcover:
```code
> W/ExposureNotification( 3899): Advertising not supported, error code=ERROR_BLUETOOTH_NOT_SUPPORTED [CONTEXT service_id=236 ]
  I/ExposureNotification( 3899): ExposureServiceInternalService.stopTracing [CONTEXT service_id=236 ]
  I/ExposureNotification( 3899): User turn off scanning. [CONTEXT service_id=236 ]
  I/ExposureNotification( 3899): Stopping scanning. [CONTEXT service_id=236 ]
```

On Xperia, there was only an informational fail, maybe not so important:
```code
  I/ExposureNotification(25204): Start advertising, started=true [CONTEXT service_id=236 ]
  I/ExposureNotification(25204): AlarmManagerImpl.opportunisticSchedule called, delay=664000ms [CONTEXT service_id=236 ]
  I/ExposureNotification(25204): ScheduledExecutorImpl.schedule called, delay=664000ms [CONTEXT service_id=236 ]
  I/ExposureNotification(25204): scheduling daily task dispatcher [CONTEXT service_id=236 ]
> I/ExposureNotification(25204): Start advertising failed with TOO_MANY_ADVERTISERS [CONTEXT service_id=236 ]
  I/ExposureNotification(25204): Settings updated bluetooth enabled: true, location enabled: true [CONTEXT service_id=236 ]
  I/ExposureNotification(25204): Settings enabled, re-enabling scanning and advertising. [CONTEXT service_id=236 ]
  I/ExposureNotification(25204): Re-enabling scanning and advertising. [CONTEXT service_id=236 ]
```

Then the app crashed on something apparently different:
```code
  E/AndroidRuntime(28248): FATAL EXCEPTION: main
  E/AndroidRuntime(28248): Process: cz.covid19cz.erouska, PID: 28248
  E/AndroidRuntime(28248): java.lang.RuntimeException: Failed to call observer method
  E/AndroidRuntime(28248): 	at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
  E/AndroidRuntime(28248): 	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
  E/AndroidRuntime(28248): 	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
  E/AndroidRuntime(28248): 	at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37)
  E/AndroidRuntime(28248): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
  E/AndroidRuntime(28248): 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
  E/AndroidRuntime(28248): 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
  E/AndroidRuntime(28248): 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
  E/AndroidRuntime(28248): 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
  E/AndroidRuntime(28248): 	at androidx.fragment.app.Fragment.performStart(Fragment.java:2736)
  E/AndroidRuntime(28248): 	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
  E/AndroidRuntime(28248): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1206)
  E/AndroidRuntime(28248): 	at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2236)
  E/AndroidRuntime(28248): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2009)
  E/AndroidRuntime(28248): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1965)
  E/AndroidRuntime(28248): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
  E/AndroidRuntime(28248): 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
  E/AndroidRuntime(28248): 	at android.os.Handler.handleCallback(Handler.java:739)
  E/AndroidRuntime(28248): 	at android.os.Handler.dispatchMessage(Handler.java:95)
  E/AndroidRuntime(28248): 	at android.os.Looper.loop(Looper.java:211)
  E/AndroidRuntime(28248): 	at android.app.ActivityThread.main(ActivityThread.java:5389)
  E/AndroidRuntime(28248): 	at java.lang.reflect.Method.invoke(Native Method)
  E/AndroidRuntime(28248): 	at java.lang.reflect.Method.invoke(Method.java:372)
  E/AndroidRuntime(28248): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
  E/AndroidRuntime(28248): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
  E/AndroidRuntime(28248): Caused by: java.lang.NoSuchMethodError: No virtual method getSystemService(Ljava/lang/Class;)Ljava/lang/Object; in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar)
> E/AndroidRuntime(28248): 	at cz.covid19cz.erouska.ext.ContextKt.isLocationEnabled(Context.kt:30)
  E/AndroidRuntime(28248): 	at cz.covid19cz.erouska.utils.DeviceUtils.isLocationEnabled(DeviceUtils.kt:23)
  E/AndroidRuntime(28248): 	at cz.covid19cz.erouska.ui.dashboard.DashboardVM.onStart(DashboardVM.kt:83)
  E/AndroidRuntime(28248): 	at java.lang.reflect.Method.invoke(Native Method)
  E/AndroidRuntime(28248): 	at java.lang.reflect.Method.invoke(Method.java:372)
  E/AndroidRuntime(28248): 	at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
  E/AndroidRuntime(28248): 	... 24 more
```

Context.kt:
```code
  29  fun Context?.isLocationEnabled(): Boolean {
> 30      val locationManager = this?.getSystemService(LocationManager::class.java) ?: return false
  31      return LocationManagerCompat.isLocationEnabled(locationManager)
  32  }
```

According to [StackOverflow](https://stackoverflow.com/questions/43487868/java-lang-nosuchmethoderror-no-virtual-method-getsystemservice) this also needs v6+,
so there are probably more incompatible parts in the code.

**Comment by brozkeff** [comment]
For curiosity I tried the above linked APK on my two ancient Android 5 phones.
Doogee X5 Pro and Prestigio PSP3508DUO, both Android 5.1.

The APK installed OK and asked for update of Google Play Services. That apparently added Exposure Notification API to the system. It however enabled that API only on the Doogee. It did NOT installed the proper API on the Prestigio probably due to some HW incompatibliity. Therefore even after updating Google Play Services on the Prestigio eRouška did not allow to continue due to missing API.

On the Doogee, however, the app was registered as the EN compatible app and was able during the activation phase to actually activate the EN API.

However then after being activated the app crashes immediately after start. However the EN API is still on on the phone.

If I disable bluetooth the eRouška manages to briefly open and show the home screen including info that it somehow managed to download the database.

And the Google Android screen "Exposure Notificatisons" screen really displays "1 exposure check".

It appears to me that _actually_ the Android via Google Play services after eRouška activates the EN API starts sending and receiving the beacons, and if the bluetooth is temporarily disabled eRouška may even manage to download the database of the infected IDs and MAYBE in case infection is detected Android may even manage to notify the user. However the UI of eRouška itself is unreachable since it crashes on start.

Since the EN API works independently on whether the particular app is running or not the system may actually work on the Doogee however I am not sure if running eRouška periodically is needed to download the fresh list of infected IDs or the Google Play Services can somehow fetch this data independently as well.

**Comment by brozkeff** [comment]
However what I find interesting that on very ancient Sony Xperia S (2012) which originally had Android 2.3 and officially supported Android up to 4.1 I use a custom ROM (nAOSPROM) based on Android 8.1 including sideloaded Google Services and it appears eRouška works perfectly even on such an ancient phone!
