### ISSUE TITLE
Incorect number of performed tests in the "Actual" tab

### ISSUE THREAD

**Issue by kalab-oto** [covid19cz/erouska-android#357]
The number of performed tests in the "Actual" tab is one day behind the number of confirmed positives. App shows the data exactly from https://onemocneni-aktualne.mzcr.cz/covid-19
![Snímek z 2020-09-21 10-13-24](https://user-images.githubusercontent.com/13303725/93745491-ecff4b00-fbf3-11ea-9408-1384f64901f4.png)

![Snímek z 2020-09-21 13-05-22](https://user-images.githubusercontent.com/13303725/93759771-23949000-fc0b-11ea-9eaa-4a0b65a19592.png)
![Snímek z 2020-09-21 13-05-18](https://user-images.githubusercontent.com/13303725/93759775-242d2680-fc0b-11ea-91d6-1d2efbe947a9.png)

In this case 14785 tests were performed on **19.9.** but 985 confirmed cases on **20.9.** But app assigns both numbers to "yesterday" - 20.9.

![Screenshot_20200921-102135](https://user-images.githubusercontent.com/13303725/93759360-538f6380-fc0a-11ea-9479-fc1ccd986207.png)

This leads to a misinterpretation of the proportion of tests performed and cases confirmed per day.

**Comment by davidvavra** [comment]
@kalab-oto I checked the numbers today and they are the same as on MZCR website. Maybe it was some glitch on the server side. Can you check again?

**Comment by haldyr** [comment]
Problem is that yesterday is not yesterday :)

see image:
![image](https://user-images.githubusercontent.com/5140211/94001878-6edca900-fd99-11ea-8621-f1ebf6a80861.png)

**Comment by davidvavra** [comment]
I see. I added it to our internal bug tracker. We will also accept a PR for this.

**Comment by marekaf** [comment]
Just to clarify - we just take this json https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/zakladni-prehled.json at 3am every day, persist it and serve it for the mobile apps, we don't refetch it during the day. 

see https://github.com/covid19cz/erouska-backend/blob/main/internal/functions/coviddata/download-covid-data-total.go#L67

**Comment by kalab-oto** [comment]
If I understand it correctly, the problem is in source data, where tests count are updated once per day around 18:00, but confirmed cases twice (around 18:00 and 1:00), so same date of update of both is only between 18 - 1. On the webpage the date is written correctly ("k datu"), but in json there is only one date (the latter) and `provedene_testy_vcerejsi_den` is delayed by one day before evening update.

**Comment by davidvavra** [comment]
Fix for this is now released to beta. Contact david.vavra@erouska.cz, if you want to test it.
