### ISSUE TITLE
Application don't want start without google apps.

### ISSUE THREAD

**Issue by vitstradal** [covid19cz/erouska-android#358]
Are Google apps essential for eRouska?  I tried to run it on Lineage Os. Besides eRouška I don't know any application which can't run without GApps (yes, google maps) even Waze can, so why eRouška? Yes, I miss notification with Mattermost, but it can run and work.

**Comment by davidvavra** [comment]
Exposure Notifications API is part of Google Play services. Plus it checks for Google Play Protect certification, so it probably don't work if you sideload Google Play Services to uncertified devices like newest Huawei devices.

**Comment by vandus** [comment]
@vitstradal I use Lineage OS as well and I have Google apps installed. You can install them https://wiki.lineageos.org/gapps.html

**Comment by vitstradal** [comment]
@vandus Thanks for comment. I use Lineage OS **because** it doesn't contain Google apps. I only wander how it comes that only eRouska needs Google apps. Every other app I need can run without gaps. Even Google's Waze. 

I understand that set of users who don't  trust Google AND kind of trust Czech government is not so big. Probably only me.

**Comment by vandus** [comment]
Sure, I kind of thought it was the reason. Well, yeah, as David said, the app is based on an API that Google developed and the way to use it is by using Google apps.

**Comment by davidvavra** [comment]
Yes, it doesn't work without GApps, we can't do anything about it, if we want to use Google/Apple API. Same reason why it doesn't work on new Huawei phones.
