### ISSUE TITLE
Show approx. time of Contact

### ISSUE THREAD

**Issue by PN99** [covid19cz/erouska-android#360]
Hello,
From various sources I understood that notification of "covid contact" contains only date of contact. Not even approximate time. In API must be some timestamps. I am a bit aware that it will make more panic than neccessary and makes bad ad for the app. Typical use case. You go by public transport to work, you go somewhere for lunch, after work you go shopping than you go to fitness and have some bier with friend during evening. You get ALERT about that day (some days later) and what? Was it in work, public transportation, in shopping center, fitness or restaurant? If you know exact (or at least approx.) time you can remember that you stood in quee in shopping center all people had masks and social distance was fair enough, it might not be so bad. Or it was in restaurant, you ask friend if he has issue, if not, maybe someone who was easting at next table. Anyway if your contact was in the evening you don´t need to call people who met during morning. I hope you understand what I mean.

**Comment by davidvavra** [comment]
The API just gives us date, not time. It's designed this way to protect privacy of the infected.
