### ISSUE TITLE
Slack link

### ISSUE THREAD

**Issue by dvoramik** [covid19cz/erouska-android#367]
Hi!
I wanted to join your slack but I encountered two issues.

The link is pointing to the wrong URL - https://github.com/covid19cz/erouska-android/blob/develop/covid19cz.slack.com

I would send you a PR but I am not sure if the right link (assuming its https://covid19cz.slack.com) is correct.
On the correct link, I am not able to sign in. You can reproduce this error with the following step:
* click `Continue with Google` button
* select google account
* `Sorry, you entered an incorrect email address or password.` error occurs
![image](https://user-images.githubusercontent.com/43810414/93918286-65592f80-fd0c-11ea-9695-54cbecf62506.png)

**Comment by davidvavra** [comment]
Hi, the Slack is invite only. I can invite you, tell me please how you want to help the COVID19CZ initiative.

**Comment by dvoramik** [comment]
That's reasonable. I don't think I can contribute that much. I was just curious
