### ISSUE TITLE
Home Icon (nav_dashboard) badge dot always red

### ISSUE THREAD

**Issue by vanous** [covid19cz/erouska-android#383]
I had no idea that badge dot on eRouška Home icon in bottom_nav has any meaning and obviously, that it should be green...:

`if (isRunning && passesRequirements()) R.color.green else R.color.red`

Which is not my case:

<img src="https://user-images.githubusercontent.com/3680926/94653483-ec556b80-02fb-11eb-977d-bf3275d5f451.jpg" width=200>
<img src="https://user-images.githubusercontent.com/3680926/94653479-eb243e80-02fb-11eb-9699-a4b37b5ecc95.jpg" width=200>
<img src="https://user-images.githubusercontent.com/3680926/94653475-ea8ba800-02fb-11eb-99a2-25181b85ce3e.jpg" width=200>
<img src="https://user-images.githubusercontent.com/3680926/94653470-e95a7b00-02fb-11eb-9db8-802aba9e1b01.jpg" width=200>
<img src="https://user-images.githubusercontent.com/3680926/94654318-2b37f100-02fd-11eb-9b01-8a968092d443.jpg" width=200>

Android 8.0.0, patch security level July 1. 2020
Model: SM-G935F
eRouška and Google services versions as per above screenshots.

Please indicate and document (in app and  on [website](https://erouska.cz/caste-dotazy#zname-chyby)) what requirements must be fulfilled and that this can mean an error + what kind of issues can one expect..

Thank you

**Comment by davidvavra** [comment]
Hi, this was a bug and it was already fixed. Update to version 2.1.688 and it icon should be green.

**Comment by vanous** [comment]
Are you sure it is fixed? Note green badge, but disabled BT. 2.1.588

<img src="https://user-images.githubusercontent.com/3680926/94657391-b0250980-0301-11eb-867f-b88fafdb91ba.jpg" width=200>

**Comment by vanous** [comment]
Also, documentation should mention this.

**Comment by davidvavra** [comment]
The bug was that the dot was always red. That's fixed. This is a different issue - the dot shows only when eRouška is enabled or disabled, but ignores other externalities like turned off Bluetooth. Create a separate issue for this.
