### ISSUE TITLE
Zavádějící popis počtu testů

### ISSUE THREAD

**Issue by literakl** [covid19cz/erouska-android#385]
Zobrazujete "počet testů za včerejší den", jenže to jsou data ze včerejška za předchozí den. 

Viz https://onemocneni-aktualne.mzcr.cz/covid-19
"Provedené testy
1 347 141
(+ 11 115 za 28.09.)"

![EjJ_5IxWkAAm8hw](https://user-images.githubusercontent.com/6383287/94679457-6b5c9b00-0320-11eb-9cb5-3f8fcdd3ab7a.jpg)

Viz diskuse:
https://twitter.com/lukenukem78/status/1311233192955916288

**Comment by davidvavra** [comment]
Duplikát issue #357
