### ISSUE TITLE
Podezřele nízké hodnoty v exposure checks

### ISSUE THREAD

**Issue by tehcaster** [covid19cz/erouska-android#391]
Zdravím,

koukal jsem v nastavení androidu na seznam exposure checks a zarazilo mě, že v každém (jeden denně) za posledních 16 dní je Number of keys vždy mezi 1000 a 1100. Přijde mi to málo a divné že to neroste, jestliže toto je počet klíčů, které byly reportovány jako nakažené a aplikace je stáhla ze serveru a nechala telefon prohledat na klíče, které v poslední době potkal, viz [1]. V telefonu manželky vidím podobná čísla s výjimkou 25.9. kdy bylo klíčů přes 8000, a také mi podobná čísla kolem 1000 potvrdilo několik známých. Je to v pořádku, nebo to znamená, že aplikace správně nestahuje/nedává ke kontrole kompletní databázi nakažených?

BTW psal jsem to i na twitteru [2]

Díky.

[1] https://www.coronawarn.app/en/faq/#keys_matches
[2] https://twitter.com/vbabka_cz/status/1313823020797038592

**Comment by davidvavra** [comment]
Taky mám počty klíčů kolem 1000, je to zvláštní. Co na to @stepansonsky ?

**Comment by nijel** [comment]
Taky vidím čísla kolem 1000, jenom 25.9. je víc

**Comment by tehcaster** [comment]
Tak jsem ze zdrojáků aplikace vytáhl, že data tahá zřejmě odsud: https://storage.googleapis.com/exposure-notification-export-qhqcx/ a zdekódoval si ty protobuffery, a fakt ty počty záznamů TemporaryExposureKey odpovídají. Takže ten export vypadá rozbitě :(

**Comment by davidvavra** [comment]
Analyzovali jsme to v teamu a závěr je takový:

Stahují se vždycky jenom přírůstky, ne klíče všech nakažených. A server má minimální dávku po 1000 klíčích, i když jich 1000 není. A my ještě nemáme 1000 klíčů za den, takže jsme na tom dolním limitu. Není to ale přesně 1000 kvůli batchování. Tzn. to že to je každý den kolem 1000 je v pořádku, až přesáhneme počty klíčů za den větší než 1000, poroste to. Což se může stát brzo, dneska spouštíme automatické posílání kódů pro eRoušku všem nakaženým SMSkou.
