### ISSUE TITLE
Matoucí informace při upozornění na kontakt

### ISSUE THREAD

**Issue by OndraM** [covid19cz/erouska-android#392]
Ahoj,
při upozornění na kontakt se na jedné obrazovce zobrazují protichůdné matoucí informace, viz screenshot.

Hádám, že dolní informace se může týkat aktualizace posledních záznamů. Pak by ale ten text měl být doplněn buď o něco jako "za poslední den". Případně by se v případě nedávného kontaktu neměl zobrazovat vůbec. 

Takhle to může u lidí vzbudit pochybnosti, jestli aplikace funguje správně.

![2020-10-08 11 56 53](https://user-images.githubusercontent.com/793041/95443940-81401080-095d-11eb-97f8-27407a44f383.png)

**Comment by davidvavra** [comment]
O tomhle víme, v kódu už to je fixed, bude to v dalším releasu odstraněné ta věta dole.
