### ISSUE TITLE
No "risky encounters" notification

### ISSUE THREAD

**Issue by orangesunny** [covid19cz/erouska-android#399]
I have two _risky encounters_ so far, I got no notification about them.

Installed the first app version, then updated version-by-version.

app 2.1.588, official Android 10 with security update from 1/9/2020 at Samsung S9+

**Comment by davidvavra** [comment]
It's s known issue, it was fixed by #395 . The update is in review.

**Comment by orangesunny** [comment]
Thanks!

*Potential fix* of something in the code looks pretty soon to close the issue as fixed. I hope it works.

When is the next release planned?

**Comment by davidvavra** [comment]
It's in review by Google/Apple. OK I will reopen until it's released.

**Comment by orangesunny** [comment]
Thank you for the information; I hope for the quick review, and that fix will work.

Many people around me have the same problem, so I was just awaiting duplicates like #400 from other users. The open issue may prevent that, or not.

**Comment by davidvavra** [comment]
The update is now live, update to 2.1.601
