### ISSUE TITLE
Warning shown until user submits (even by mistake)

### ISSUE THREAD

**Issue by pe-pan** [covid19cz/erouska-android#401]
Warning shown until user submits (even by mistake):
1. How it behaves: Once the warning is shown, I can either click 'VICE INFORMACI' or 'ZAVRIT' button. To see details of the contact (like the date), I need to click the former. If I (by mistake) clicked the latter button first, this warning is closed for good and I have no chance to see it again along with the details I might be interested in.
2. Expected behavior: 
  - either to have a clear confirmation that I'm going to remove the Warning for good and I'll never be able to see its details again - a simpler solution
  - or to have a list of all previous warnings found (if not all, then within certain period in the past) so I can open the warning again and again to review all its details (or even have multiple warnings) until I get rid of it for good - a more sofisticated solution

Found on Android OnePlus 6 (Android 10, OxygenOS 10.3.5) with eRouška 2.0 from 2020-09-28

**Comment by davidvavra** [comment]
If you close the warning, you can still see the information under "Riziková setkání" under three dots on the main screen.

**Comment by pe-pan** [comment]
I found it; still, not intuitive at all. How about redesigning app UI a bit?

**Comment by davidvavra** [comment]
You are right that the three dots should not have important features like this. We are in the process of redesigning the home screen, see issue #345 about details how it will look.
