### ISSUE TITLE
Zero keys detected

### ISSUE THREAD

**Issue by kucik** [covid19cz/erouska-android#404]
For all days in history i see 0 keys. Even though we both have enabled erouska and BT at home. The other phone shows thousands of keys.
![Screenshot_20201013-210045](https://user-images.githubusercontent.com/6491536/95905149-c4a0e180-0d98-11eb-98d0-85c0c3c6ac07.png)
![Screenshot_20201013-205347](https://user-images.githubusercontent.com/6491536/95905156-c7033b80-0d98-11eb-838b-1df947efd95d.png)
![Screenshot_20201013-205336](https://user-images.githubusercontent.com/6491536/95905159-c7033b80-0d98-11eb-8f7a-c69795c54a81.png)

**Comment by davidvavra** [comment]
That's strange, you should definitely see thousands of keys every day. Key download is probably not working properly. Anything unusual about your phone? Custom ROM, sideloaded Google services, battery saver, data saver or something like that?

**Comment by kucik** [comment]
Nothing custom afaik. Updating and installing only through google shop. No
data limitations. Battery saving mode run only whe battery is low.
What other info i can give you?

M<<

Dne út 13. 10. 2020 21:19 uživatel David Vavra <notifications@github.com>
napsal:

**Comment by davidvavra** [comment]
Not sure, nobody had this problem yet AFAIK. I would try to reinstall if that helps (if you see some keys next day). Your eRouška is not working anyway, so don't be afraid about losing data.

**Comment by kucik** [comment]
About download: Other phone shows same hash. Does it tell something about
keys download status?

M<<

Dne út 13. 10. 2020 21:30 uživatel David Vavra <notifications@github.com>
napsal:

**Comment by davidvavra** [comment]
Not really

**Comment by davidvavra** [comment]
@kucik Any updates?

**Comment by kucik** [comment]
I've unistalled, and installed erouska again. Still the same. There is
similar issues described :
https://github.com/corona-warn-app/cwa-app-android/issues/744
 But I still didn't find a way to make it work.

BTW wouldn't it be easier to write czech?

M<<

Dne so 17. 10. 2020 10:33 uživatel David Vavra <notifications@github.com>
napsal:

**Comment by davidvavra** [comment]
Ano, můžeme psát česky. Nic moc mě nenapadá, ta issue na německé appce taky nepomohla. Někdo tam píše, že to možná bylo malým volným místem na telefonu, nemáte ten případ? Ještě mě napadají různé data savery/battery savery, které by nějak znemožňovaly fungování aplikace. Nepoužíváte něco podobného? Jinak nebude to častý problém, na supportu jsme měli kromě vás jenom jeden podobnný případ.

**Comment by kucik** [comment]
Co se pameti tyce, tak telefon tvrdi, ze ma stale nekolik GB volnych jak na
karte, tak v interni pameti. Nepouzivam zadny data/battery saver, ale
obcas mam pocit, ze ma tenhle telefon neco takoveho snad primo v systemu,
protoze napriklad nektere zalohy dat ci aktualizace neni schopen dokoncit,
pokud se neprobudi display.

M<<

st 21. 10. 2020 v 12:40 odesílatel David Vavra <notifications@github.com>
napsal:

**Comment by davidvavra** [comment]
Mohl byste projít nastavení a zkusit ty věci v systému povypínat, případně dát pro eRoušku výjimku? Návody pro různé telefony jsou zde: https://dontkillmyapp.com/

**Comment by kucik** [comment]
Prosel jsem to a zrovna na tento telefon zadny navod nepasuje. Nicmene
vypnul jsem to jedine nastaveni optimalizace spotreby, ktere tam bylo.
Uvidime.

st 21. 10. 2020 v 13:58 odesílatel David Vavra <notifications@github.com>
napsal:

**Comment by brozkeff** [comment]
Jelikož jde o Android 6 a poslední aktualizaci i bezpečnosti si výrobce telefonu uráčil udělat v lednu 2017 (3 roky a 9 měsíců neaktualizovaný telefon!!), tak je velmi pravděpodobné, že krom kritických bezpečnostních chyb, co v tom telefonu budou, včetně zranitelností samotného Bluetooth protokolu, tam budou i desítky dalších nevyřešených bugů, na které se výrobce (iGet) úplně vykašlal :-(

**Comment by brozkeff** [comment]
Podle nějakých zpráv na netu se ale zdá, že k telefonu existuje i nějaká verze Androidu 7 (https://www.here-shop.cz/blackview-bv6000-odladeny-android-7) a stálo by možná za pokus zkusit přes OTA nebo ručně tan dostat poslední dostupnou verzi ROMky od výrobce.

**Comment by kucik** [comment]
Diky za tip. Nejspis ho radeji zahodim.

st 21. 10. 2020 v 21:41 odesílatel Martin Malec <notifications@github.com>
napsal:

**Comment by kucik** [comment]
Vsechny optimalizace vypnutý, ale tenhle mobil s tim prostě nefunguje.
Stale 0.

M<<

Dne čt 22. 10. 2020 9:54 uživatel Martin Kucko <kucko.martin@gmail.com>
napsal:
