### ISSUE TITLE
Riskantní kontakty nalezeny i v případě, kdy žádné nebyly

### ISSUE THREAD

**Issue by jaryn** [covid19cz/erouska-android#405]
Verze: 2.1.588

Objevila hláška o nebezpčených kontaktech ve dnech 5., 6., 7. a 10. 10. přitom já byl skoro celý týden (od 6. - 12. 9.) v domě (měl jsem jinou nemoc) a jsem si celkem jistý, že jsem neměl žádné kontakty s nikým pozitivně testovaným na COVID-19.

**Comment by davidvavra** [comment]
Tady GitHub není úplně support kanál, napište prosím na info@erouska.cz, tam přesně tohle vysvětlují.
