### ISSUE TITLE
Error "http 400" 

### ISSUE THREAD

**Issue by rightwords** [covid19cz/erouska-android#406]
Hello,

in many cases, we can see problems while using the code from the hygiene station. Code is "http 400" and text "Nepodařilo se nám odeslat data."

Screenshot: https://prnt.sc/uz4w9l

Thank you for checking it. 

L.

**Comment by davidvavra** [comment]
Yes we are aware about it, it's a production issue we are currently investigating. Fix should hopefully be on the server side without the need for app update.

**Comment by davidvavra** [comment]
The issue should be fixed and you should no longer see HTTP 400 in the app.
