### ISSUE TITLE
Matoucí text

### ISSUE THREAD

**Issue by literakl** [covid19cz/erouska-android#408]
Druhá věta, že mám postupovat podle pokynů pracovníka hygieny, mě docela zmátla. Aplikace je anonymní, takže jak mě může pracovník hygieny kontaktovat? Doporučuji větu smazat. Naopak pod ní přidejte jednoduchý nadpis "Co teď?", který uvodí dvě varianty, zda pociťuji příznaky či ne.

![Screenshot_20201014-102123_eRouka](https://user-images.githubusercontent.com/6383287/96034292-95a27280-0e61-11eb-8328-5af7dd896f75.jpg)

**Comment by davidvavra** [comment]
Pracovník hygieny vás nemůže kontaktovat skrze eRoušku, ale je možné že vás vytrasují jinak, pokud se znáte s nakaženým. Ale chápu, že ten text může být matoucí. Co na to náš UX @vlastimirhavlicek ?

**Comment by vlastimirhavlicek** [comment]
Taky souhlasím, že je matoucí. Ukazuje se nám to i na uživatelských testech. Jeho doplnění si vyžádalo MZ.

**Comment by literakl** [comment]
Ten nadpis Co teď? by za mě dost pomohl. To je první otázka, která člověka napadne, když dostane upozornění. Požadovaný text hygienou jde dát jako první možnost. Hrubý náčrt:

Dne XY jste se setkali s Covid osobou.
Co teď?
1) Pokud vás bude kontaktovat HS, řiďte se jejím pokyny
2) Mám příznaky
3) Nemám příznaky

**Comment by radeksvarz** [comment]
Dostal jsem nedavno risky encounter. Ma prvni reakce byla: kde to bylo? V ten den jsem byl v autoservisu a v jednom malem kramku. Radeji jim zavolam a upozornim take je na mozny kontakt.

Nicmene mohu horem dolem vysvetlovat svym paranoidnim pribuznym, jak anonymne erouska funguje, ale tenhle text to proste zabiji. 

a) navrh zmeny textu:

Dne 14.10.2020 jste se setkali s osobou, u ktere bylo potvrzeno onemocneni COVID-19.  Ta osoba dala lidem okolo sebe skrze erousku anonymne vedet, ze se s ni potkali. Ano tak byla laskava. Jak je to mozne? (odkaz na infografiku)

Co ted?
Je mozne, ze Vas bude kontaktovat HS, pokud si na vas ona osoba vzpomnela osobne.  
...

b) erouska by mela mit v sobe onu infografiku, jak anonymne funguje: https://erouska.cz/img/infografika.png

**Comment by davidvavra** [comment]
Hello everyone, we are preparing a new major version which will contain redesigned screen for risky encounter, which fixes this issue. Is anyone interested for alfa testing this? If so, we need to whitelist your account in Google Play. Send me your primary Google account, either here or to email david.vavra@erouska.cz

**Comment by davidvavra** [comment]
Redesign of this screen is now released into beta. Contact david.vavra@erouska.cz, if you want to test it.

**Comment by literakl** [comment]
Mám verzi 2.2.661, v Play se mi zobrazuje výzva na přeinstalaci netestovací verzí, takže to bude testovací verze.

Bohužel nemám jak otestovat, protože se mi stará setkání již nezobrazují. Mohli byste sem nahrát aspon screenshot?

**Comment by davidvavra** [comment]
Jsou to 3 screeny:
![device-2020-11-08-173653](https://user-images.githubusercontent.com/395884/98470932-1b0f0d80-21e9-11eb-82a2-81b329262a47.png)
![device-2020-11-08-173718](https://user-images.githubusercontent.com/395884/98470938-1cd8d100-21e9-11eb-9744-d3a1fcaa48fb.png)
![device-2020-11-08-173728](https://user-images.githubusercontent.com/395884/98470940-1f3b2b00-21e9-11eb-91d7-1317414d80c9.png)

**Comment by literakl** [comment]
Díky, lepší.

Dne ne 8. 11. 2020 17:38 uživatel David Vavra <notifications@github.com>
napsal:
