### ISSUE TITLE
Enhancement: allow to download and install the app from a non-official Google Play Store

### ISSUE THREAD

**Issue by pe-pan** [covid19cz/erouska-android#409]
There is a demand to download the app for phones that are based on Android but don't have Google services enabled (e.g. Huawei brand). So either
- publish the app also in the other stores (Huawei AppGallery, etc.)
- publish the app binaries in a public link to install it on rooted phones

**Comment by davidvavra** [comment]
EN API is tied with Google Play Services and Google is disabling it on devices which are not "Google Play Protect certified", see here: https://support.google.com/googleplay/answer/7165974?hl=en Meaning it won't work even if you sideload Google services somehow.

But app binaries are free to download here at GitHub at "Actions" tab for every build.
