### ISSUE TITLE
Which license covers this source code

### ISSUE THREAD

**Issue by slp** [covid19cz/erouska-android#42]
Hi,

Thanks for working on this and making it public. Given that every country would benefit from a variant of this application, it would be great to create an international community around this project.

I haven't found any references to a license in this repository. Could you please clarify which one covers the source code on it?

Thanks and please keep up the good work.

**Comment by Foxlik** [comment]
Hi Sergio,
I guess we have not had time to think about this. Our goal is to help. Please give us a day, we'll figure it out. 
Cheers,
Tomas

**Comment by davidvavra** [comment]
I vote for MIT license, it's easiest for everyone.

**Comment by slp** [comment]
> I vote for MIT license, it's easiest for everyone.

:+1: That would be amazing. I tend to prefer copyleft licenses, but given the incompatibilities of the GPL with the AppStore, having this under a liberal license would be great.

Just my two cents.
Thanks a lot for your work!
