### ISSUE TITLE
Avoid "eRouska is paused" notification if other ENS app is active

### ISSUE THREAD

**Issue by radeksimko** [covid19cz/erouska-android#422]
I understand that may be part of a minority of users, but especially until the [data sharing problem](https://github.com/covid19cz/erouska-android/issues/349) is resolved I expect there will be more people like me, who have more than one ENS app installed.

I use the UK's [NHS Covid-19](https://play.google.com/store/apps/details?id=uk.nhs.covid19.production) app where I have tracing enabled and I'm getting the following notification repeatedly from eRouska:

![Screenshot_20201020-170802_2](https://user-images.githubusercontent.com/287584/96614522-1e089380-12f8-11eb-907b-6ea2697053fc.png)

I think the notification _is_ helpful and I would _want_ to keep getting it, but obviously not in this context.

The only option I realistically have now is to either uninstall it until I travel back to 🇨🇿   or suppress that notification category, which does not seem ideal to me.

Is there any API that would allow you to check whether there is any other active ENS app and avoid sending that notification in such case?

**Comment by davidvavra** [comment]
I'm not aware about an API for checking other ENS apps. This will be solved with data sharing, we are already working on it in branch `feature/efgs`.

**Comment by davidvavra** [comment]
We are working of integration of EFGS: https://github.com/eu-federation-gateway-service/efgs-federation-gateway

This is an EU initiative, led by the German team. Because of Brexit, not sure about the UK.

**Comment by radeksimko** [comment]
Gotcha, I suppose there isn't much you can do then, if there isn't any API available.

I assume that uninstalling eRouska or suppressing notification is the only solution until/unless EFG or similar project allows data sharing, which is understandable.

Thank you for all the work you do btw.!
