### ISSUE TITLE
Erouska interferes with Garmin Smartwatches connection to Android phone

### ISSUE THREAD

**Issue by kosek** [covid19cz/erouska-android#425]
Hi,

we have observed on two different phones with two different watches connected (VivoActive 3 and Instict) that after application is installed BT connection between phone and watches is randomly lost, sometimes it helps to re-enable BT, restart watches etc. Instinct watches freezed couple of times for several minutes, once even completely. Such weird behavior went away after e-Rouska has been uninstalled.

**Comment by davidvavra** [comment]
We have few reports of connection issues with some BT devices. Much less than in eRouška 1.0. Unfortunately this is beyond our control, Bluetooth is managed completely by the Google (Google Play Services app), not by us.
