### ISSUE TITLE
announcement servers questions

### ISSUE THREAD

**Issue by omichalek** [covid19cz/erouska-android#428]
Hi all,

As a Sailfish OS user I use the Contrac program https://github.com/llewelld/harbour-contrac which aims for server-side compatibility with the German https://github.com/corona-warn-app

My questions:
1) is the data sharing between Czech and German authorities in place? If so, I will get warned in case of exposure, won't I?
1) if not, could you advise me on Czech server addresses and whether they are compatible?

**Comment by davidvavra** [comment]
Hi, the integration with EFGS is not done yet, but we are working on it in branch `feature/efgs`
