### ISSUE TITLE
Rizikové setkání (RIsc appointment) report - add time, not only date

### ISSUE THREAD

**Issue by petr-toman** [covid19cz/erouska-android#459]
In case of Exposure "Rizikové setkání" has been reported to user, would be helpfull to state not only the date, but also the hour or part of the day, to help user to realize which kind of meet it could be and self-evaulate severity of risk.

V připadě hlášení "Rizikové setkání" by bylo užitečné uvádět nejen datum ale i hodinu, nebo část dne, kdy k setkání došlo. To by pomohlo uživateli lépe si uvědomit o jaké setkání šlo a vyhodnotit si tak míru rizika.

To overcome possible privacy issues would be possible to make it as opt-in (opt-out) settings value, available as user setting. (in a style as is used in Whatsapp - "last seen/online" feature)

**Comment by davidvavra** [comment]
Unfortunately this is not under our control. It's a feature of Google/Apple API. They don't give us time, only date of the encouter. The reason is the privacy of the infected person.

**Comment by petr-toman** [comment]
Understood, thanks for quick reply.
