### ISSUE TITLE
Funkcionalita pro zahranici

### ISSUE THREAD

**Issue by amirzolal** [covid19cz/erouska-android#51]
Prosim implementujte sledovani odkud clovek prijizdi ze zahranici, karanteni opatreni pro lidi co prijizdeji ze Saska (25 pripadu / 100k) nebo Durynska (21 pripadu / 100k) jsou po prijezdu do CR (19 pripadu / 100k). Na druhou stranu by bylo dobre vedet ktery clovek se nachazel v nejakem znamem hotspotu. Hranice vecne zavrene byt nemuzou a kamionaci stejne jezdi, takze i ty je potreba sledovat.

**Comment by Foxlik** [comment]
@amirzolal
To co popisujes je spis pro appku mapy.cz. erouska s polohou cloveka vubec nepracuje.

Smyslem erousky je jen a pouze pomoci dohledat lidi, v jejichz bezprostredni blizkosti se nakazeny pohyboval. A to s maximalnim ohledem na soukromi uzivatele.

**Comment by davidvavra** [comment]
Ano, my cíleně s polohou nepracujeme, myslíme si že potom lidé budou aplikaci víc věřit a nainstaluje si jí velké množství lidí.
