### ISSUE TITLE
Drobné opravy v textu Nápověda

### ISSUE THREAD

**Issue by machj** [covid19cz/erouska-android#76]
Ahoj, nemám přístup k úpravě textů, proto reportuji takto. V aplikaci v okně Nápověda (O aplikaci) navrhuji následující úpravy:

"váš telefon automaticky vypíná některé ..." - správně by měla věta začínat velkým písmenem, jako ostatní odstavce

 "na celostátní telefonní lince: 1212 nebo webu Ministerstva zdravotnictví ČR - https://koronavirus.mzcr.cz" - navrhuji odstranit dvojtečku a pomlčku

"Další uživatelé se ani nedozví kdy a kde přišli" - před "kdy a kde" by měla být čárka

"i přes to má jejich použití smysl" - velké I na začátku věty

"ID eRoušky lze spojit pouze s konkrétním zařízením a telefonním číslem uživatele. a to pouze u těch ID ..." - čárka namísto tečky, resp. doporučuji celou větu upravit, aby bylo zřejmé, kdo může spárovat ID a tel. číslo: "ID eRoušky může s konkrétním telefonním číslem uživatele spojit pouze pracovník hygienické stanice, a to pouze u těch ID ...". 

Následující větu "Do systému se přihlašují pomocí osobního (...) a hesla." lze vypustit, zkrátí to text, pro běžného uživatele irelevantní až matoucí.

 "Aplikace žádná data sama nikam neodesílá." doporučuji změnit (de facto ani není pravda, např. při registraci...): "Aplikace nasbíraná data odešle hygienické stanici pouze až na vaši žádost."

"v souladu se Zákonem o ochraně osobních údajů a GDPR" - zákon byl zrušen, správně má být "v souladu se Zákonem o zpracování osobních údajů č. 110/2019 Sb. a GDPR"

"v Zásadách ochrany soukromí aplikace a webu eRouška" - asi má být "na webu eRouška"

"Ano. v aplikaci je možné" - velké písmeno na začátku věty "V aplikaci"

Ještě k záložce kontakty: zde je "nebo vás zajímá jak funguje?" - chybí čárka před ", jak funguje?". Do kontaktů bych doporučil přidat i odkaz na "Zásady zpracování osobních údajů", které budou směřovat na adresu erouska.cz/gdpr, patřičnou stránku s informací o zpracovávaných odkazech, právech uživatele a s kontaktem na DPO aj. připravit. Použití /gdpr je zvykem, uvedení těchto údajů je povinné.

**Comment by davidvavra** [comment]
@machj: Uděláte si prosím fork repa, upravíte soubor strings.xml a pošlete pull request?

**Comment by machj** [comment]
Provedeno, snad je to takto v pořádku.

**Comment by davidvavra** [comment]
Děkuji, mergnuto.
